# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelling',
            name='collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelling',
            name='seat_no',
            field=models.IntegerField(),
        ),
    ]
