# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0002_auto_20180206_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
