# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0003_booking_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='Airline.UserAge'),
        ),
    ]
