# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0005_auto_20180207_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Booking')),
            ],
        ),
    ]
